[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/functions/v1/*"
  to = "https://akclwguqzeijscftatqp.supabase.co/functions/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
